package it.polimi.ingsw.util.supportclasses;

public enum ClientState {
    WELCOME_STATE, ERROR_JOINING_STATE, SETUP_STATE, NOT_PLAYING_STATE, PLAYING_STATE, DRAWING_STATE, LAST_TURN_STATE ,END_GAME_STATE, KICKED_STATE, LOST_CONNECTION_STATE
}
