package it.polimi.ingsw.util.supportclasses;

public enum ClientState {
    LOBBY_STATE, ERROR_JOINING_STATE, GAME_SETUP_STATE, NOT_PLAYING_STATE, PLAYING_STATE, DRAWING_STATE, LAST_TURN_STATE ,END_GAME_STATE, KICKED_STATE, LOST_CONNECTION_STATE
}
